import mongoose from 'mongoose';

export const products = [
  {
    id: 'product1_unique',
    sellerId: new mongoose.Types.ObjectId(),  
    image: 'https://example.com/taylor-dress.jpg',
    title: 'Taylor Swift Inspired - Vintage Floral Dress',
    price: 1499,
    size: 'M',
    sustainable: true,
    quantity: 1,
    description: "Inspired by Taylor Swift's iconic vintage style, this floral dress combines elegance with a touch of country charm. Perfect for casual outings or dressy occasions.",
    discount: '10% Off on first purchase',
    tagline: "Taylor’s Signature Look",
    review: 'Stylish and comfortable',
  },
  {
    id: 'product2_unique',
    sellerId: new mongoose.Types.ObjectId(),
    image: 'https://example.com/kanye-jacket.jpg',
    title: 'Kanye West Streetwear - Oversized Bomber Jacket',
    price: 3599,
    size: 'L',
    sustainable: false,
    quantity: 1,
    description: "Channel Kanye West's streetwear vibe with this oversized bomber jacket. Crafted for comfort and style, it’s ideal for urban fashion lovers who want to stand out.",
    discount: 'Flat 15% Off',
    tagline: 'Essentials for Kanye Fans',
    review: 'High-quality material and comfortable',
  },
  {
    id: 'product3_unique',
    sellerId: new mongoose.Types.ObjectId(),
    image: 'https://example.com/beyonce-glam-dress.jpg',
    title: 'Beyoncé Glamour - Sequined Bodycon Dress',
    price: 4499,
    size: 'S',
    sustainable: false,
    quantity: 1,
    description: "Step into the spotlight with a sequined bodycon dress inspired by Beyoncé's red-carpet looks. The perfect choice for parties and evening events.",
    discount: 'Exclusive 10% Off',
    tagline: "Queen Bey's Glam Picks",
    review: 'Perfect for a glamorous look',
  },
  {
    id: 'product4_unique',
    sellerId: new mongoose.Types.ObjectId(),
    image: 'https://example.com/rihanna-jumpsuit.jpg',
    title: 'Rihanna Bold Style - Casual Denim Jumpsuit',
    price: 2299,
    size: 'M',
    sustainable: true,
    quantity: 1,
    description: "Embrace Rihanna's bold and edgy style with this casual denim jumpsuit. Comfortable yet fashionable, it’s perfect for a standout streetwear look.",
    discount: 'Flat 20% Off',
    tagline: "Riri’s Street Style",
    review: 'Unique design and comfortable',
  },
  {
    id: 'product5_unique',
    sellerId: new mongoose.Types.ObjectId(),
    image: 'https://example.com/bieber-hoodie.jpg',
    title: 'Justin Bieber Vibes - Casual Oversized Hoodie',
    price: 1799,
    size: 'L',
    sustainable: true,
    quantity: 1,
    description: "Stay cozy and cool in this oversized hoodie inspired by Justin Bieber's casual style. Perfect for everyday wear and available in multiple colors.",
    discount: 'Extra 5% Off',
    tagline: "Bieber’s Laid-Back Style",
    review: 'Very comfortable for everyday wear',
  },
  {
    id: 'product6_unique',
    sellerId: new mongoose.Types.ObjectId(),
    image: 'https://example.com/ariana-coat.jpg',
    title: 'Ariana Grande Luxe - Elegant Faux Fur Coat',
    price: 3299,
    size: 'S',
    sustainable: true,
    quantity: 1,
    description: "Stay warm and chic with this faux fur coat inspired by Ariana Grande's glamorous style. Perfect for winter evenings or any time you want to turn heads.",
    discount: 'Winter Sale 10% Off',
    tagline: "Ariana’s Luxe Picks",
    review: 'Very warm and stylish',
  },
  {
    id: 'product7_unique',
    sellerId: new mongoose.Types.ObjectId(),
    image: 'https://example.com/drake-varsity-jacket.jpg',
    title: 'Drake Streetwear - Varsity Jacket',
    price: 2399,
    size: 'M',
    sustainable: false,
    quantity: 1,
    description: "This varsity jacket brings Drake's iconic street style into your wardrobe. Pair it with jeans or joggers for a versatile, everyday look.",
    discount: '20% Off on Orders Over ₹2000',
    tagline: "OVO Style Essentials",
    review: 'Stylish and versatile',
  },
];
